spring.application.name=estudio-spring

service.products=json

## Spring Datasource Configuration
app.name=Sistema de productos
app.version=1.0.0
app.author=Jacob
app.language=es
app.country=Chile


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.maximum-pool-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000

management.endpoints.web.exposure.include=*

spring.cloud.azure.active-directory.redirect-uri-template={baseUrl}/login/oauth2/code/azure

spring.cloud.azure.active-directory.enabled=true
spring.cloud.azure.active-directory.profile.tenant-id=${TENANT_ID}
spring.cloud.azure.active-directory.credential.client-id=${CLIENT_ID}
spring.cloud.azure.active-directory.credential.client-secret=${CLIENT_SECRET}

# Fuerza a Azure a habilitar el flujo interactivo de Login Web
spring.cloud.azure.active-directory.application-type=web-application
spring.cloud.azure.active-directory.base-uri=https://login.microsoftonline.com/

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs


server.port=8080