spring.application.name=estudio-spring

service.products=json

## Spring Datasource Configuration
app.name=Sistema de productos
app.version=1.0.0
app.author=Jacob
app.language=es
app.country=Chile




server.port=8080